# Generated by Django 3.2.5 on 2021-11-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.PositiveIntegerField(default=1, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.PositiveIntegerField(default=1, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.PositiveIntegerField(default=1, max_length=10, null=True),
        ),
    ]
