# Generated by Django 3.2.5 on 2022-02-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220208_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
